# Generated by Django 2.2.6 on 2020-07-18 10:56

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Apointment_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.0'), max_digits=20, null=True)),
                ('Date', models.CharField(max_length=120)),
                ('Time', models.CharField(max_length=300)),
                ('accepts', models.CharField(blank=True, default='Pending', max_length=150, null=True)),
                ('st', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Doctors')),
                ('patients', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pa', to='user.patients')),
            ],
            options={
                'ordering': ['-st'],
            },
        ),
        migrations.CreateModel(
            name='Medical_test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(max_length=500)),
                ('Weight', models.CharField(max_length=500)),
                ('blood_sugar', models.CharField(max_length=500)),
                ('body_tempreture', models.CharField(max_length=500)),
                ('medical_prescription', models.TextField(max_length=700)),
                ('st', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Doctors')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient', to='user.patients')),
            ],
            options={
                'ordering': ['-st'],
            },
        ),
        migrations.CreateModel(
            name='Decline_note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Note', models.TextField(max_length=500)),
                ('st', models.DateTimeField(auto_now_add=True)),
                ('book_apointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='book', to='doc.Book_Apointment_model')),
                ('doctors', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.Doctors')),
            ],
            options={
                'ordering': ['-st'],
            },
        ),
    ]
