# Generated by Django 2.2.6 on 2020-07-22 09:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0002_send_report_to_pharmacy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug_payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='medical_test',
            name='u_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
