# Generated by Django 2.2.6 on 2020-07-22 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0003_auto_20200722_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_report_to_pharmacy',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical', to='doc.Medical_test'),
        ),
    ]
