# Generated by Django 2.2.6 on 2020-07-22 14:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0005_medical_test_book_apointment_mo'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_apointment_model',
            name='uu_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
