# Generated by Django 2.2.6 on 2020-07-24 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_pham_model_category'),
        ('doc', '0007_remove_send_report_to_pharmacy_pham'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='send_report_to_pharmacy',
            name='medical',
        ),
        migrations.AddField(
            model_name='send_report_to_pharmacy',
            name='Pham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pham', to='user.Pham_model'),
        ),
    ]
