# Generated by Django 2.2.6 on 2020-07-24 09:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_pham_model_category'),
        ('doc', '0009_auto_20200724_0957'),
    ]

    operations = [
        migrations.CreateModel(
            name='confirm_drug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confirm', models.CharField(max_length=120)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('Pham', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pham', to='user.Pham_model')),
                ('Send_pharmacy', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pham', to='doc.Send_report_to_pharmacy')),
            ],
            options={
                'ordering': ['-time'],
            },
        ),
        migrations.DeleteModel(
            name='Drug_payment',
        ),
    ]
