# Generated by Django 2.2.6 on 2020-07-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0012_auto_20200725_1051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_apointment_model',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Doctors'),
        ),
        migrations.AlterField(
            model_name='book_apointment_model',
            name='patients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pa', to='user.patients'),
        ),
        migrations.AlterField(
            model_name='confirm_drug',
            name='Pham',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pham', to='user.Pham_model'),
        ),
        migrations.AlterField(
            model_name='confirm_drug',
            name='Send_pharmacy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pham', to='doc.Send_report_to_pharmacy'),
        ),
        migrations.AlterField(
            model_name='decline_note',
            name='book_apointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='doc.Book_Apointment_model'),
        ),
        migrations.AlterField(
            model_name='decline_note',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Doctors'),
        ),
        migrations.AlterField(
            model_name='medical_test',
            name='Book_Apointment_mo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Book_Apointment', to='doc.Book_Apointment_model'),
        ),
        migrations.AlterField(
            model_name='medical_test',
            name='doctors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Doctors'),
        ),
        migrations.AlterField(
            model_name='medical_test',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient', to='user.patients'),
        ),
        migrations.AlterField(
            model_name='send_report_to_pharmacy',
            name='medical',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='medical', to='doc.Medical_test'),
        ),
        migrations.AlterField(
            model_name='send_report_to_pharmacy',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.patients'),
        ),
    ]
