# Generated by Django 2.2.6 on 2021-07-11 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0015_chat_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='reciever',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reciever', to='user.Doctors'),
        ),
    ]
