# Generated by Django 2.2.6 on 2021-07-11 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0016_auto_20210711_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='user.patients'),
        ),
    ]
