# Generated by Django 2.2.6 on 2021-07-11 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0017_auto_20210711_0234'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat_model',
            options={},
        ),
        migrations.AddField(
            model_name='chat_model',
            name='re_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
        migrations.AddField(
            model_name='chat_model',
            name='se_id',
            field=models.CharField(blank=True, max_length=400, null=True),
        ),
    ]
