# Generated by Django 2.2.6 on 2021-07-11 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0019_auto_20210711_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat_model',
            old_name='reciever',
            new_name='other_user',
        ),
        migrations.RenameField(
            model_name='chat_model',
            old_name='sender',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='chat_model',
            name='Sender_back',
            field=models.CharField(default='false', max_length=400),
        ),
    ]
