# Generated by Django 2.2.6 on 2021-07-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0020_auto_20210711_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_model',
            name='Sender_back',
            field=models.CharField(default=False, max_length=400),
        ),
        migrations.AlterField(
            model_name='chat_model',
            name='reciever_back',
            field=models.CharField(default=False, max_length=400),
        ),
    ]
