# Generated by Django 2.2.6 on 2021-07-12 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0022_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='Dr_notify',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Dr_notify', to='user.Doctors'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='pq_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pq_message', to='user.patients'),
        ),
    ]
