# Generated by Django 2.2.6 on 2021-07-12 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doc', '0023_auto_20210712_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='viewed',
            field=models.CharField(default=False, max_length=500),
        ),
    ]
