# Generated by Django 2.2.6 on 2020-07-27 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_remove_pham_model_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='accountant_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('First_name', models.CharField(max_length=500)),
                ('Other_name', models.CharField(max_length=500)),
                ('email', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('image', models.ImageField(default='T.png', upload_to='profile_pic')),
            ],
        ),
    ]
