# Generated by Django 2.2.6 on 2020-07-29 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_accountant_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user.Category'),
        ),
    ]
