# Generated by Django 2.2.6 on 2021-07-13 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20200729_1222'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctors',
            name='status',
            field=models.CharField(default='False', max_length=400),
        ),
    ]
